import fs from 'fs/promises';
import path from 'path';
import { loadSkillsDirectory } from './config.js';

const CATALOG_PATH = 'skills/skill-advisor/references/skill-catalog.md';

/**
 * Extract description from SKILL.md frontmatter
 * @param {string} content - File content
 * @returns {string} Description or default message
 */
export function extractDescription(content) {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) {
    return 'No description available';
  }

  const frontmatter = frontmatterMatch[1];

  // Match description field - handle quoted and unquoted values
  const descMatch = frontmatter.match(/description:\s*["']?(.+?)["']?(?:\n|$)/);
  if (descMatch) {
    // Handle multi-line descriptions (collapse whitespace)
    let desc = descMatch[1].trim();

    // If description continues on next lines (indented), capture that too
    const multiLineMatch = frontmatter.match(/description:\s*["']?(.+?)["']?\n(\s{2,}.+?)(?:\n(?!\s)|$)/s);
    if (multiLineMatch) {
      desc = (multiLineMatch[1] + ' ' + multiLineMatch[2]).replace(/\s+/g, ' ').trim();
    }

    return desc.replace(/\s+/g, ' ');
  }

  return 'No description available';
}

/**
 * Generate skill catalog markdown
 * @param {string} configDir - Path to config directory
 * @param {object} [deps] - Optional dependencies for testing
 * @returns {Promise<string>} Generated markdown
 */
export async function generateCatalog(configDir, deps = {}) {
  const {
    loadSkillsDirectory: loadDir = loadSkillsDirectory,
    readFile = fs.readFile,
    writeFile = fs.writeFile
  } = deps;

  const directory = await loadDir(configDir);

  // Group skills by category
  const skillsByCategory = {
    primary: [],
    contextual: [],
    experimental: []
  };

  for (const skill of directory.skills) {
    // Skip skill-advisor itself
    if (skill.name === 'skill-advisor') continue;

    // Read SKILL.md to get description
    const skillMdPath = path.join(configDir, 'skills', skill.name, 'SKILL.md');
    let description = 'No description available';

    try {
      const content = await readFile(skillMdPath, 'utf-8');
      description = extractDescription(content);
    } catch (err) {
      console.warn(`  Warning: Could not read ${skillMdPath}`);
    }

    if (skillsByCategory[skill.category]) {
      skillsByCategory[skill.category].push({
        name: skill.name,
        category: skill.category,
        description: description,
        invoke: `/${skill.name}`
      });
    }
  }

  // Generate markdown
  let markdown = `# Skill Catalog

> This file is auto-generated by \`ai-config-sync catalog\`. Do not edit manually.
> Last updated: ${new Date().toISOString()}

`;

  const categoryOrder = ['primary', 'contextual', 'experimental'];
  const categoryTitles = {
    primary: 'Primary Skills',
    contextual: 'Contextual Skills',
    experimental: 'Experimental Skills'
  };

  for (const category of categoryOrder) {
    const skills = skillsByCategory[category];
    if (skills.length === 0) continue;

    markdown += `## ${categoryTitles[category]}\n\n`;

    for (const skill of skills) {
      markdown += `### \`${skill.name}\`\n\n`;
      markdown += `${skill.description}\n\n`;
      markdown += `**Invoke:** \`${skill.invoke}\`\n\n`;
    }
  }

  // Write catalog
  const catalogPath = path.join(configDir, CATALOG_PATH);
  await writeFile(catalogPath, markdown);
  console.log(`Generated catalog with ${directory.skills.length - 1} skills at ${catalogPath}`);

  return markdown;
}
